### ISSUE TITLE
About page Find Out More - need to add more community links

### ISSUE THREAD

**Issue by Silka123** [switch2osm/switch2osm#100]
Propose a on page Find Out More in section "Getting help" add still 2 points:
1. Forum OpenStreetMap (https://forum.openstreetmap.org/) (many languages)
2. Telegram-channel @OpenStreetMapOrg (https://telegram.me/OpenStreetMapOrg) (list of local chapters OSM Telegram-channels) (https://wiki.openstreetmap.org/wiki/List_of_OSM_centric_Telegram_accounts)

**Comment by SomeoneElseOSM** [comment]
It does make sense to update that page.  Over at https://github.com/switch2osm/switch2osm.github.io/issues/76#issuecomment-562857752 I suggested "There's definitely a case for pointing people who come to switch2osm at the OSM community, Depending on who they are an appropriate place might be OSMF's US-focused "Welcome Mat", or https://openstreetmap.community , or a specific community resource or local chapter".

I'd definitely agree that the forum should be added.  Even though it's not a "free and open resource" like IRC is, we also ought to mention Telegram, particularly in places around the world where it is the usual discussion mechanism (e.g. Latin America).  The problem is that it's not easy to link to - a web browser won't understand tg://resolve?domain=OpenStreetMapOrg , for example.

**Comment by Silka123** [comment]
As it seems to me, in some life situations, it is better to do something first, even if something simple, but it will work and help now. Than than never realize the most a remarkable and steep idea. As it seems to me, there is no reason that would prevent the placement of a static link to the list of Telegram channels in WikiOSM.

**Comment by SomeoneElseOSM** [comment]
I've updated some of the "find out more" links (including the new forum).
I've not added to any of the Telegram (or Discord) sites - I'm not convinced it'd be a good idea.
