### ISSUE TITLE
Enable piwik analytics

### ISSUE THREAD

**Issue by pnorman** [switch2osm/switch2osm#18]

**Comment by ThomasG77** [comment]
Now, it's Matomo instead of Piwik. Integration is really simple (https://developer.matomo.org/guides/tracking-javascript-guide) but the server part is more problematic.
We can:
* use third party to provide Matomo server part but pricing at least for official website can cost a lot depending of the traffic https://matomo.org/pricing/ (any other alternatives as long it's not Google Analytics...)
* use self-hosting but who can host the server part? The OSM foundation could help? poke @systemed

**Comment by systemed** [comment]
OSMF has a Matomo instance I believe - cc @Firefishy
