### ISSUE TITLE
docker compose asking for testers ?

### ISSUE THREAD

**Issue by mattiashem** [switch2osm/switch2osm#210]
Hi
I made a small docker compose for OSM.
And in that did break out 
- OSM
- Tile imports
- Postgress
- Web 

https://github.com/mattiashem/osm

Is there is interest a will move on adding better sync between importer and osm.
And then move on making a helm chart to deploy it to kuberntets.?

Any other ides ?

**Comment by SomeoneElseOSM** [comment]
Hello,

Perhaps it's worth writing an OSM diary entry so that more people will see it?  I'm not sure how many people will see it here.

What does it do that e.g. https://github.com/switch2osm/switch2osm.github.io/blob/master/serving-tiles/using-a-docker-container.md does not do?

Best Regards,

Andy

**Comment by SomeoneElseOSM** [comment]
Closing this; there's nothing else actionable here (yet).
