### ISSUE TITLE
Any idea to use webp instead of png output for tiles?

### ISSUE THREAD

**Issue by 2803media** [switch2osm/switch2osm#212]
Hi all on my self host I want to use webp instead png but can't find a way to make it work, any recommandation to do that? I don't see anything in the tutorial to make this change.
Thanks a lot

**Comment by Firefishy** [comment]
Would require changes to mod_tile and/or renderd

**Comment by SomeoneElseOSM** [comment]
As @Firefishy says, it's not something that the underlying software supports right now, but it is pretty easy to build from source, so you could make whatever changes you wanted to a local copy of mod_tile and use that instead.  I wrote a few notes on the "build from source" process [here](https://wiki.openstreetmap.org/wiki/User:SomeoneElse/map.atownsend.org.uk/Setup#Zoom_levels_above_20) but to be honest it's pretty much _exactly_ what you'd expect.

You could perhaps perhaps bodge something that converted a newly created .png file into a webp one, but I'm not really sure what the benefit of that would be.

What was your reason for wanting webp files instead of .png ones?

**Comment by 2803media** [comment]
Thanks for your reply the aim of my reflexion is to optimise file transfert and size of the images, I made some test and the gains are between 30% and 60%...

**Comment by SomeoneElseOSM** [comment]
I'll close this here since https://github.com/openstreetmap/mod_tile/issues/301 is open.
