### ISSUE TITLE
How to safely remove OSM installation

### ISSUE THREAD

**Issue by 2803media** [switch2osm/switch2osm#219]
Hi all 

I want to reset my installation and for so I need to safely remove everything install here https://switch2osm.org/serving-tiles/manually-building-a-tile-server-debian-11/

Do you know where I can find a tutorial to do this uninstallation?

Thanks

**Comment by SomeoneElseOSM** [comment]
> Do you know where I can find a tutorial to do this uninstallation?

I don't think that there is one specifically written for this, but there is [generic](https://askubuntu.com/questions/187888/what-is-the-correct-way-to-completely-remove-an-application#187891) information out there that might help.  Questions you'll need to ask include "is this packaged that I installed as part of these instructions needed for something else"?  It's likely that "libapache2-mod-tile" and "renderd" aren't, but lots of other software in the big "apt install" list probably will be.

What I'd tend to do personally if I I was installing something on a server as a test would be one of:

- snapshot that server so that it could easily be restored to the previous state
- install in a virtual machine, or use something like Docker, to provide containerisation and allow test changes to be thrown away
- Deploy in a single-use VPS, which can similarly be thrown away afterwards.

If someone were to write a guide like this (or even a generic one that pointed to other information such as the askubuntu question above) we could certainly consider adding it, but I don't think that anyone has any immediate plans to do this.

**Comment by 2803media** [comment]
@SomeoneElseOSM thanks for your input as this installation is not on a test server but in production, a step by step uninstallation maybe useful ;)

I will make some uninstall test with snapshot backups, not the better way but a safe one...
