### ISSUE TITLE
Instructions for building a tile server do not work on 16.04

### ISSUE THREAD

**Issue by matthijsmelissen** [switch2osm/switch2osm#26]
The installation instructions do not work on Ubuntu 16.04.

The tutorial specifies that 'these packages work with Ubuntu Linux versions 12.04 LTS (Precise Pangolin) and above', so I'd expect them to work on 16.04 too.

The instructions instruct adding the package libapache2-mod-tile by adding the kakrueger PPA. This PPA however is not available for 16.04.

**Comment by pnorman** [comment]
For the revised instructions I intend to
- build nothing from source that is available from repos
- split the content differently into multiple pages. loading OSM data will be on one page and running a tileserver on another
- drop 14.04 and earlier support

**Comment by SomeoneElseOSM** [comment]
@matthijsmelissen I've created a pull request for the 16.04 page from https://switch2osm.org/manually-building-a-tile-server-16-04-2-lts/ (coverted to Markdown).  That _will_ work on 16.04.  I'm not 100% convinced that the "packages" pages will work anywhere any more.  The 16.04 ex-Wordpress page already does "everything possible from Ubuntu packages" (but deliberately doesn't rely on an external PPA).

**Comment by matthijsmelissen** [comment]
Great work! I think we can close this now #39 is merged.

**Comment by SomeoneElseOSM** [comment]
There's still a problem at the Jekyll side I believe - http://switch2osm.github.io/serving-tiles/manually-building-a-tile-server-16-04-2-lts/ doesn't work for me either, just as it doesn't for https://github.com/ThomasG77 .

The wider issue of "what to do with the 'packages' instructions" still applies too - both here and at the Wordpress site.  If did change the https://switch2osm.org/serving-tiles/building-a-tile-server-from-packages/ page to be less obviously wrong, but there are still some gotchas in there that need ironing out (and to be honest we probably shouldn't be suggesting that such old packaged versions are used by anyone).

**Comment by SomeoneElseOSM** [comment]
Just to finish off the thread here - I believe that the Jekyll site is now at the same place as the Wordpress site (and in fact the Jekyll site is now live), so any old issues re the Jekyll site shouldn't be valid any more.  That said, I haven't done a 16.04 build for a while, and it's possible that a "node" change may have broken it.  If anyone tests it and finds a problem, we can fix it, but I suspect that most new deployers will be on 18.04 or another OS altogether and going via Docker.

The "with packages" instructions did actually work the last time I tested it (shortly after writing the comments above) but it's even more ancient history and that version of Ubuntu server LTS isn't supported by them any more.  I suspect a good time to get rid of it would be when we do instructions for the next LTS version, next year.

**Comment by Firefishy** [comment]
My recommendation would be to only ever support the latest LTS release of Ubuntu, which is currently Ubuntu 18.04.

**Comment by SomeoneElseOSM** [comment]
> ... and it's possible that a "node" change may have broken it. If anyone tests it and finds a problem, we can fix it, but I suspect that most new deployers will be on 18.04 or another OS altogether and going via Docker.

Give that I've just had to update the 18.04 instructions for a node change, I suspect that either the same will need to be done here or (when perhaps 20.04 comes out) we remove them altogether.  If we do decide to keep them a big fat warning at the top would make sense.  I can see where @Firefishy is coming from above, although I'd probably be less absolutist than that.

I'll reopen this due to the like "node change breakage" mentioned above.

**Comment by SomeoneElseOSM** [comment]
Since 2020 the approach I've taken with "old" versions like https://switch2osm.org/serving-tiles/manually-building-a-tile-server-16-04-2-lts/ , that will still work but are for outdated OSes is:

- Remove them from the menus so no-one will stumble across them by mistake
- Add a caveat saying how and why this is outdated.

I think that we're up to date at the moment, although in the future:
- It'd be good to add a Debian 12 page, and to update the "updating" pages with e.g. osmium version info.
- Everything that describes OSM Carto will need updating when / if that switches to flex per https://github.com/gravitystorm/openstreetmap-carto/pull/4431 .
- The Ubuntu 18.04 page will need to be retired

I don't think that there is anything that needs doing particularly for this issue.
