### ISSUE TITLE
Pink tiles

### ISSUE THREAD

**Issue by systemed** [switch2osm/switch2osm#8]
By far the most common s2o-related query on the #osm/#osm-dev IRC channels is "pink tiles" - i.e. tileserver not working, people don't know where to go next.

It would be good to have a troubleshooting page/section running through the possible causes of this, and explaining how to diagnose and fix.

**Comment by pnorman** [comment]
I'd like to build checks into the guides which make sure that each part works before going onto the next. e.g. after loading with osm2pgsql, check that tables exist with psql, after mod_tile, `curl -I host/0/0/0.png`.

**Comment by SomeoneElseOSM** [comment]
Now that the setup of renderd / mod_tile is more automatic there's less to go wrong here, but e.g. "Next, point a web browser at: http://yourserveripaddress/hot/0/0/0.png" has been in the guides from almost the start.

Recently where people have problems it's usually due to trying to improvise around the instructions ("I can't wait and have a big server so I'll do the whole planet not just one country").

Some parts are opaque and do not fail safe ("scripts/get-external-data.py" gives no feedback and fails if NE is having an off day), but (touch wood) that hasn't been an issue for a while.
